import { effectRegistry, EFFECT_MODEL_VERSION } from "./long-term-effects";
import type { MetricRecord, SourceRecord } from "./types";

const source = (id:string,title:string,institution:string,url:string,status:SourceRecord["status"],confidence:SourceRecord["confidence"],summary:string,method:string,limitations:string[]):SourceRecord => ({ id,title,institution,url,dataYear:2025,legalYear:2026,status,confidence,summary,method,limitations,checkedAt:"2026-07-13" });
export const effectModuleSources: SourceRecord[] = [
  source("source-effect-engine","Wirkungs-Engine Milestone 8","DE-SIM Projekt","https://kevni92.github.io/de-sim-docs/","modell","mittel","Versionierter Modellvertrag für direkte, indirekte, zeitabhängige und langfristige Szenariowirkungen.","Gewichtete Bevölkerungsauswertung, modulare Zeitpfade, getrennte Rückkopplungen und breite Unsicherheitsbänder.",["Keine sichere Prognose.","Kein makroökonomisches Gleichgewichtsmodell."]),
  source("source-effect-kita","Kindertagesbetreuung: Plätze, Personal und Inanspruchnahme","Statistisches Bundesamt","https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Soziales/Kindertagesbetreuung/_inhalt.html","amtlich","hoch","Amtliche Ausgangsgrößen zur Kindertagesbetreuung; lokale Ausfalltage und Öffnungszeiten sind nicht vollständig enthalten.","Beobachtete Baseline und Plausibilitätsrahmen, nicht kausaler Effektwert.",["Keine einrichtungsgenaue Zuordnung im Bevölkerungslauf."]),
  source("source-effect-labour","Arbeitsmarkt- und Erwerbsbeteiligungsevidenz","Institut für Arbeitsmarkt- und Berufsforschung","https://www.iab.de/","modell","mittel","Externe Evidenz für Arbeitsangebot, Erwerbsbeteiligung und zielgruppenspezifische Reaktionen.","Literaturwerte werden als Band und Szenarioannahme übertragen.",["Übertragbarkeit hängt von Maßnahme, Zielgruppe und Zeitraum ab."]),
  source("source-effect-health","Arbeitsunfähigkeit und Gesundheit bei der Arbeit","Bundesanstalt für Arbeitsschutz und Arbeitsmedizin","https://www.baua.de/","amtlich","mittel","Ausgangsinformationen zu Arbeitsunfähigkeit; bewertet werden nur vorgegebene Veränderungen.","Vermiedene Tage werden in Arbeitsstunden übersetzt.",["Keine Diagnose- oder Branchendifferenzierung."]),
  source("source-effect-productivity","Produktivität und langfristige Wachstumseffekte","Deutsche Bundesbank","https://www.bundesbank.de/","modell","niedrig","Makroökonomische Evidenz als Rahmen für breite Sensitivitätspfade.","Exogene jährliche Produktivitätsannahme mit verzögertem Aufbau.",["Kein Gleichgewichts-, Preis-, Lohn- oder Zinsmodell."]),
  source("source-effect-education","Bildung, Abschlüsse und Qualifikation","Statistisches Bundesamt","https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/_inhalt.html","amtlich","mittel","Amtliche Bildungsbaselines; zusätzliche Abschlusswirkungen bleiben Szenarioannahmen.","Kohortenbezogene nicht monetäre Spannweitenrechnung.",["Keine Kompetenz-, Schulform- oder Übergangsmodellierung."]),
  source("source-effect-administration","Erfüllungsaufwand und Bürokratiekosten","Nationaler Normenkontrollrat","https://www.normenkontrollrat.bund.de/","modell","mittel","Methodischer Rahmen zur Trennung von Einführungskosten und laufendem Erfüllungsaufwand.","Zeitersparnis wird separat als nicht monetäre Wirkung und modellierter Zeitwert ausgewiesen.",["Kein konkretes Regelungsvorhaben hinterlegt."]),
  source("source-effect-migration","Migration und Integration","Bundesamt für Migration und Flüchtlinge","https://www.bamf.de/","amtlich","mittel","Externe Ausgangsdaten; im synthetischen Bevölkerungslauf fehlt derzeit eine ausreichend belegte Zielvariable.","Keine Monetarisierung bis Zielpopulation und Kalibrierung dokumentiert sind.",["Keine pauschale Übertragung externer Gruppenmittelwerte."]),
  source("source-effect-demography","Bevölkerungsvorausberechnung und Demografie","Statistisches Bundesamt","https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Bevoelkerungsvorausberechnung/_inhalt.html","amtlich","mittel","Amtliche demografische Szenarien sind keine kausale Reformprognose.","Geburten-, Alters- und Sozialausgabenpfade bleiben bis zur Kohortenfortschreibung unberechnet.",["Keine Fertilitäts-, Mortalitäts- oder Wanderungskohorten im aktuellen Modell."]),
  source("source-effect-fiscal","Fiskalische Rückkopplung aus Einkommen und Wertschöpfung","DE-SIM Projekt","https://kevni92.github.io/de-sim-docs/","annahme","niedrig","Durchschnittliche Abgabenquote zur getrennten Darstellung möglicher Rückflüsse.","Nur positive modellierte Einkommen und Wertschöpfung werden mit einer transparenten Szenarioquote multipliziert.",["Keine Steuerarten-, Beitragszweig- oder Grenzsatzdifferenzierung."]),
  source("source-effect-infrastructure","Öffentliche Investitionen und Infrastrukturwirkungen","Sachverständigenrat zur Begutachtung der gesamtwirtschaftlichen Entwicklung","https://www.sachverstaendigenrat-wirtschaft.de/","modell","niedrig","Externe Evidenz für verzögerte Investitionswirkungen mit hoher Kontextabhängigkeit.","Direkte Ausgaben und verzögerter Multiplikator werden getrennt ausgewiesen.",["Kein Projektportfolio, keine Baukapazität und keine Preisreaktion."]),
];
const statusMap:Record<string,MetricRecord["status"]>={"amtlich-beobachtet":"amtlich",modellrechnung:"modell",szenarioannahme:"annahme","externe-evidenz":"modell","nicht-berechnet":"unbekannt","nicht-ausreichend-belegt":"unbekannt"};
const confidenceMap:Record<string,MetricRecord["confidence"]>={"amtlich-beobachtet":"hoch",modellrechnung:"mittel",szenarioannahme:"niedrig","externe-evidenz":"mittel","nicht-berechnet":"niedrig","nicht-ausreichend-belegt":"niedrig"};
export const effectModuleMetrics: MetricRecord[] = effectRegistry.map((module) => ({
  id:`metric-effect-${module.id}`,label:module.title,category:"Indirekte und langfristige Wirkungen",description:module.description,unit:"Mrd. € pro Jahr und nicht monetäre Wirkung",status:statusMap[module.evidenceStatus],confidence:confidenceMap[module.evidenceStatus],dataYear:module.dataYear,legalYear:module.legalYear,sourceIds:module.sourceIds,formula:"Gesamtwirkungₜ = direkte Erstwirkungₜ + indirekte Wirkungₜ + Langfristwirkungₜ + Rückkopplungₜ",parameters:module.parameters.map((item)=>({name:item.label,value:`${item.defaultValue} ${item.unit}`,sourceId:item.sourceId})),calculation:[{label:"Zielpopulation",expression:module.targetPopulation},{label:"Direkte Wirkung",expression:module.directEffect},{label:"Indirekte Wirkung",expression:module.indirectEffect},{label:"Zeitpfad",expression:`Start ${module.timing.startYear}, Anlauf ${module.timing.rampYears} Jahre, Maximum ${module.timing.peakYear}`}],uncertainty:{kind:"range",description:module.uncertaintyModel},limitations:module.limitations,changeLog:[{date:"2026-07-13",version:EFFECT_MODEL_VERSION,note:"Milestone 8: Wirkungsmodell und Evidenzstatus eingeführt."}]
}));
export const effectSourceIds = effectModuleSources.map((item)=>item.id);
