import type { MetricRecord, SourceRecord } from "./types";

export const expenseModuleSources: SourceRecord[] = [
  {
    id: "source-citizen-benefit",
    title: "Regelbedarfe im Bürgergeld und in der Sozialhilfe 2026",
    institution: "Bundesministerium für Arbeit und Soziales",
    url: "https://bmas.bund.de/DE/Service/Presse/Pressemitteilungen/2025/fortschreibung-regelbedarfe-sozialhilfe-und-buergergeld.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Fortschreibung der Regelbedarfe für das Jahr 2026 sowie Einordnung der gesetzlichen Bedarfskomponenten.",
    method: "Die Rechts- und Leistungsstruktur wird als Baseline übernommen. Das im Simulator verwendete Gesamtaufkommen bleibt ein gerundetes föderales Aggregat.",
    limitations: ["Keine Einzelfallprüfung nach Haushaltskonstellation.", "Unterkunftskosten unterscheiden sich regional und werden nur als Index geführt."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-pension-report",
    title: "Rentenversicherungsbericht 2025",
    institution: "Bundesregierung / Bundesministerium für Arbeit und Soziales",
    url: "https://www.bundesregierung.de/breg-de/aktuelles/rentenbericht-2025-2394260",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtlicher Bericht zu Finanzentwicklung, Beitragssatz, Rentenniveau und langfristigen Annahmen der gesetzlichen Rentenversicherung.",
    method: "Demografische und finanzielle Größen begründen die Parameterstruktur. Der Simulator verdichtet sie zu einem Bundesausgaben-Aggregat.",
    limitations: ["Keine individuelle Rentenbiografie.", "Versicherungsleistungen und Bundeszuschüsse werden nicht vollständig als getrennte Finanzierungskonten geführt."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-education-finance",
    title: "Bildungsfinanzen und Ausbildungsförderung",
    institution: "Statistisches Bundesamt",
    url: "https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Bildungsfinanzen-Ausbildungsfoerderung/_inhalt.html",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Ausgangsdaten zu Bildungsausgaben und ihrer föderalen Zuordnung.",
    method: "Die Statistik dient als Struktur- und Plausibilitätsquelle; das UI verwendet ein gerundetes, enger abgegrenztes Haushaltsaggregat.",
    limitations: ["Bund, Länder und Kommunen finanzieren Bildung gemeinsam.", "Ausgabenabgrenzung und Berichtsjahre unterscheiden sich von Haushaltsansätzen."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-family-benefits",
    title: "Kindergeld und Familienleistungen 2026",
    institution: "Bundesministerium für Bildung, Familie, Senioren, Frauen und Jugend",
    url: "https://www.bmbfsfj.bund.de/bmbfsfj/themen/familie/familienleistungen/kindergeld",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Informationen zu Anspruch, Leistung und Rechtsgrundlagen des Kindergelds.",
    method: "Familienleistungen werden als monetäres Teilaggregat getrennt von der Kindertagesbetreuung geführt.",
    limitations: ["Günstigerprüfung mit Kinderfreibeträgen ist nicht Teil des Ausgabenmoduls.", "Weitere Familienleistungen werden im Aggregat zusammengefasst."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-daycare",
    title: "Kindertagesbetreuung",
    institution: "Bundesministerium für Bildung, Familie, Senioren, Frauen und Jugend",
    url: "https://www.bmbfsfj.bund.de/bmbfsfj/themen/familie/kinderbetreuung",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Informationen zu Ausbau, Qualität und föderaler Finanzierung der Kindertagesbetreuung.",
    method: "Plätze und Qualitätskosten sind getrennte Szenariotreiber des Kita-Teilaggregats.",
    limitations: ["Kommunale Gebühren und Trägerstrukturen werden nicht einzeln modelliert.", "Regionale Platzknappheit bleibt unberücksichtigt."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-health-spending",
    title: "Zahlen und Fakten zur gesetzlichen Krankenversicherung",
    institution: "Bundesministerium für Gesundheit",
    url: "https://www.bundesgesundheitsministerium.de/themen/krankenversicherung/zahlen-und-fakten-zur-krankenversicherung.html",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Kennzahlen zu Versicherten, Einnahmen und Ausgaben der gesetzlichen Krankenversicherung.",
    method: "Leistungsvolumen und Vergütungsniveau werden als getrennte Treiber des Gesundheits-Teilaggregats verwendet.",
    limitations: ["Private Krankenversicherung und Selbstzahlungen sind nicht vollständig enthalten.", "Leistungsbereiche werden nicht einzeln nach Diagnosen simuliert."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-care-benefits",
    title: "Leistungen der Pflegeversicherung im Überblick 2026",
    institution: "Bundesministerium für Gesundheit",
    url: "https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/leistungen-im-ueberblick",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Übersicht der Leistungsansprüche in der sozialen Pflegeversicherung im Jahr 2026.",
    method: "Zahl der Pflegebedürftigen und Leistungsniveau werden als getrennte Aggregattreiber modelliert.",
    limitations: ["Pflegegrade und Leistungsarten werden nicht als Einzelfälle berechnet.", "Eigenanteile und kommunale Sozialhilfe sind nur teilweise im Ausgangsaggregat enthalten."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-federal-budget-2026",
    title: "Bundeshaushalt 2026",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundesfinanzministerium.de/Web/DE/Themen/Oeffentliche_Finanzen/Bundeshaushalt/Bundeshaushalt-2026/bundeshaushalt-2026.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Haushaltsansätze des Bundes einschließlich Investitionen, Einzelplänen und ergänzenden Sondervermögen.",
    method: "Der Bundeshaushalt ist eine zentrale Plausibilitätsquelle; die App-Baseline umfasst zusätzlich gerundete Länder-, Kommunal- und Sozialversicherungsaggregate.",
    limitations: ["Soll und Ist können erheblich voneinander abweichen.", "Sondervermögen und föderale Ebenen erfordern eine konsolidierte Abgrenzung."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-defense-budget",
    title: "Bundeshaushalt digital – Einzelplan Verteidigung",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundeshaushalt.de/DE/Bundeshaushalt-digital/bundeshaushalt-digital.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Digitale amtliche Darstellung der Haushaltsansätze, darunter der Einzelplan des Bundesministeriums der Verteidigung.",
    method: "Personal, Beschaffung, Betrieb und Mittelabfluss bilden die Szenarioparameter.",
    limitations: ["NATO-Abgrenzung und Haushaltseinzelplan sind nicht identisch.", "Mehrjährige Beschaffungsvorhaben werden als Jahresaggregat vereinfacht."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-infrastructure-budget",
    title: "Investitionsoffensive im Bundeshaushalt 2026",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundesfinanzministerium.de/Web/DE/Themen/Oeffentliche_Finanzen/Bundeshaushalt/Bundeshaushalt-2026/bundeshaushalt-2026.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Angaben zu Investitionen im Kernhaushalt, Klima- und Transformationsfonds sowie Sondervermögen Infrastruktur und Klimaneutralität.",
    method: "Neuinvestitionen, Erhalt und tatsächlicher Mittelabfluss werden im Modell getrennt.",
    limitations: ["Das App-Aggregat ist enger als die gesamte Investitionssumme des Bundes.", "Planungs- und Bauverzögerungen werden nur über eine Mittelabflussquote abgebildet."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-subsidy-report",
    title: "30. Subventionsbericht der Bundesregierung",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundesfinanzministerium.de/Content/DE/Downloads/Broschueren_Bestellservice/30-subventionsbericht.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Berichterstattung zu Finanzhilfen und Steuervergünstigungen des Bundes für die Berichtsjahre 2025 und 2026.",
    method: "Finanzhilfen und Steuervergünstigungen bleiben getrennte Parameter. Zielgenauigkeit und Auslaufen sind Szenarioannahmen.",
    limitations: ["Nicht jede wirtschaftspolitische Begünstigung fällt unter die Berichtsdefinition.", "Das App-Aggregat ist nicht mit dem Gesamtvolumen des Berichts gleichzusetzen."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-migration-statistics",
    title: "Statistiken zu Migration, Asyl und Integration",
    institution: "Bundesamt für Migration und Flüchtlinge",
    url: "https://www.bamf.de/DE/Themen/Statistik/statistik-node.html",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Statistiken zu Asylverfahren, Migration und Integrationsangeboten.",
    method: "Fallzahlen und Aufgabenstruktur begründen getrennte Teilaggregate für Unterbringung, Verfahren, Integration und weitere Bereiche.",
    limitations: ["BAMF-Statistiken bilden nicht sämtliche Ausgaben von Ländern und Kommunen ab.", "Steuern und Beiträge von Zugewanderten werden nicht mit den Ausgaben saldiert."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-expense-model",
    title: "DE-SIM Modellvertrag für Ausgabenmodule",
    institution: "DE-SIM Projekt",
    url: "https://kevni92.github.io/de-sim-docs/",
    dataYear: 2025,
    legalYear: 2026,
    status: "modell",
    confidence: "mittel",
    summary: "Versionierter Vertrag für Baseline, direkte Ausgabenwirkung, Folgewirkung, Begünstigtenstruktur und Unsicherheit.",
    method: "Jedes Modul berechnet Teilaggregate getrennt, führt sie anschließend zusammen und weist die modellstufenabhängige Folgewirkung separat aus.",
    limitations: ["Noch keine repräsentative Mikrosimulation der Leistungsfälle.", "Begünstigtenanteile und Folgewirkungen sind Modellannahmen und keine Prognosen."],
    checkedAt: "2026-07-13",
  },
];

const changeLog = [
  { date: "2026-07-13", version: "0.6.0", note: "Neun priorisierte Ausgabenmodule mit gemeinsamer Modell- und Transparenzschnittstelle eingeführt." },
];

const metric = (
  id: string,
  label: string,
  description: string,
  sourceIds: string[],
  formula: string,
  parameters: MetricRecord["parameters"],
  limitations: string[],
  uncertainty: number,
  confidence: MetricRecord["confidence"] = "mittel",
): MetricRecord => ({
  id,
  label,
  category: "Ausgaben und Leistungen",
  description,
  unit: "Mrd. € pro Jahr",
  status: "modell",
  confidence,
  dataYear: 2025,
  legalYear: 2026,
  sourceIds,
  formula,
  parameters,
  calculation: [
    { label: "Baseline", expression: "A₀ = gerundetes und abgegrenztes Ausgangsaggregat" },
    { label: "Direkte Wirkung", expression: "Aₛ = Summe der getrennt berechneten Teilaggregate" },
    { label: "Folgewirkung", expression: "A = Aₛ − ΔAₛ × Sensitivität × Modellstufe" },
  ],
  uncertainty: { kind: "band", lowerPercent: -uncertainty, upperPercent: uncertainty, description: "Bandbreite für föderale Abgrenzung, Fallzahlen, Mittelabfluss und modellierte Folgewirkungen." },
  limitations,
  changeLog,
});

export const expenseModuleMetrics: MetricRecord[] = [
  metric("metric-expense-social", "Ausgaben für Bürgergeld und Unterkunft", "Regelbedarfe, Bedarfsgemeinschaften, Unterkunftskosten sowie Verwaltung und Eingliederung.", ["source-citizen-benefit", "source-federal-budget-2026", "source-expense-model"], "Aₛ = Bürgergeld(Regelbedarf, Fälle, Verwaltung) + Unterkunft(Fälle, Kostenindex)", [{ name: "Regelbedarfsniveau", value: "Index 100", sourceId: "source-citizen-benefit" }, { name: "Unterkunftskosten", value: "regional verdichteter Index", sourceId: "source-expense-model" }], ["Keine individuelle Bedürftigkeitsprüfung.", "Regionale Mieten und Heizkosten werden nicht einzeln abgebildet."], 16),
  metric("metric-expense-pension", "Bundesbezogene Rentenausgaben", "Verdichtete Wirkung von Rentenwert, Zahl der Leistungsbeziehenden, Bundeszuschuss und Referenzalter.", ["source-pension-report", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 128,4 × gewichtete Indizes × Referenzalterfaktor", [{ name: "Rentenwert", value: "Index 100", sourceId: "source-pension-report" }, { name: "Referenzalter", value: "67 Jahre", sourceId: "source-expense-model" }], ["Keine individuelle Erwerbsbiografie.", "Gesamtleistung der Rentenversicherung und Bundeshaushalt sind nicht identisch."], 12),
  metric("metric-expense-education", "Ausgaben für Bildung und Schulen", "Aggregat aus Ausgaben je Lernendem, Zahl der Lernenden, Digital- und Gebäudeinvestitionen sowie Mittelabfluss.", ["source-education-finance", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 22,6 × gewichtete Bildungsindizes × Mittelabfluss", [{ name: "Ausgaben je Lernendem", value: "Index 100", sourceId: "source-education-finance" }, { name: "Mittelabfluss", value: "100 % Baseline", sourceId: "source-expense-model" }], ["Föderale Ausgabenabgrenzung ist vereinfacht.", "Keine Schulart- oder Länderrechnung."], 24, "niedrig"),
  metric("metric-expense-family", "Ausgaben für Kitas und Familienleistungen", "Getrennte Teilaggregate für monetäre Familienleistungen und Kindertagesbetreuung.", ["source-family-benefits", "source-daycare", "source-federal-budget-2026", "source-expense-model"], "Aₛ = Familienleistungen(Niveau, Nutzung) + Kita(Plätze, Qualität)", [{ name: "Familienleistungsniveau", value: "Index 100", sourceId: "source-family-benefits" }, { name: "Betreuungsplätze", value: "Index 100", sourceId: "source-daycare" }], ["Keine individuelle Günstigerprüfung.", "Regionale Kita-Kosten und Gebühren sind nicht einzeln enthalten."], 18),
  metric("metric-expense-health", "Ausgaben für Gesundheit und Pflege", "Getrennte Gesundheits- und Pflegeaggregate mit Leistungsvolumen, Vergütung, Pflegefällen und Präventionsannahme.", ["source-health-spending", "source-care-benefits", "source-federal-budget-2026", "source-expense-model"], "Aₛ = Gesundheit(Volumen, Vergütung, Prävention) + Pflege(Fälle, Leistungsniveau)", [{ name: "Gesundheitsleistungen", value: "Index 100", sourceId: "source-health-spending" }, { name: "Pflegeleistungsniveau", value: "Index 100", sourceId: "source-care-benefits" }], ["Keine Diagnose- oder Pflegegrad-Mikrosimulation.", "Präventionsentlastung ist eine Annahme, keine sichere Einsparung."], 18),
  metric("metric-expense-defense", "Verteidigungsausgaben", "Personal, Ausrüstung, Betrieb und tatsächlicher Mittelabfluss.", ["source-defense-budget", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 71,8 × (0,4 Ausrüstung + 0,3 Personal + 0,3 Betrieb) × Mittelabfluss", [{ name: "Einzelplan und Sondervermögen", value: "Haushaltsquelle 2026", sourceId: "source-defense-budget" }], ["NATO- und Haushaltsabgrenzung unterscheiden sich.", "Mehrjährige Beschaffung wird als Jahreswert verdichtet."], 15),
  metric("metric-expense-infrastructure", "Infrastrukturausgaben", "Neue Investitionen, Erhalt und tatsächlicher Mittelabfluss.", ["source-infrastructure-budget", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 34,1 × (0,55 Neuinvestition + 0,45 Erhalt) × Mittelabfluss", [{ name: "Investitionsrahmen", value: "Bundeshaushalt und Sondervermögen", sourceId: "source-infrastructure-budget" }], ["Nicht alle öffentlichen Investitionen sind enthalten.", "Projektverzögerungen werden nur über den Mittelabfluss angenähert."], 25, "niedrig"),
  metric("metric-expense-subsidies", "Subventionen und Steuervergünstigungen", "Finanzhilfen, Steuervergünstigungen, Zielgenauigkeit und auslaufende Maßnahmen.", ["source-subsidy-report", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 41,7 × Hilfenmix × Zielgenauigkeitsfaktor × Auslauffaktor", [{ name: "Subventionssystematik", value: "30. Subventionsbericht", sourceId: "source-subsidy-report" }], ["App- und Berichtsabgrenzung sind nicht identisch.", "Mitnahmeeffekte und Zielgenauigkeit sind Szenarioannahmen."], 30, "niedrig"),
  metric("metric-expense-migration", "Ausgaben für Migration und Asyl", "Getrennte Teilaggregate für Unterbringung, Verfahren, Integration sowie Bildung und weitere Bereiche.", ["source-migration-statistics", "source-federal-budget-2026", "source-expense-model"], "Aₛ = 9,8 Unterbringung + 5,1 Verfahren + 4,4 Integration + 10,5 weitere Bereiche, jeweils mit Szenarioindex", [{ name: "Fall- und Verfahrensstruktur", value: "BAMF-Statistik", sourceId: "source-migration-statistics" }, { name: "Teilaggregate", value: "gerundete Modellbaseline", sourceId: "source-expense-model" }], ["Keine Saldierung mit Steuern und Beiträgen.", "Länder- und Kommunalausgaben sind nur als Aggregat enthalten."], 35, "niedrig"),
];
