import type { MetricRecord, SourceRecord } from "./types";

export const revenueModuleSources: SourceRecord[] = [
  {
    id: "source-vat",
    title: "Umsatzsteuer: Steuersätze nach § 12 UStG",
    institution: "Bundesministerium der Finanzen",
    url: "https://usth.bundesfinanzministerium.de/usth/2024/A-Umsatzsteuergesetz/IV-Steuer-und-Vorsteuer/Paragraf-12/inhalt.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Grundlage für den Regelsteuersatz von 19 Prozent und den ermäßigten Steuersatz von 7 Prozent.",
    method: "Die gesetzlichen Sätze werden als feste Baseline übernommen; die Aufkommensbasis bleibt eine kalibrierte Aggregatannahme.",
    limitations: ["Die konkrete Zuordnung einzelner Güter und Leistungen wird noch nicht als Warenkorb modelliert.", "Vorsteuerabzug und Steuerbefreiungen sind nur im Baseline-Aggregat enthalten."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-inheritance",
    title: "Erbschaftsteuer- und Schenkungsteuergesetz – § 19 Steuersätze",
    institution: "Bundesministerium der Justiz / Bundesamt für Justiz",
    url: "https://www.gesetze-im-internet.de/erbstg_1974/__19.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Gesetzliche Tarifstufen nach Steuerklasse und Höhe des steuerpflichtigen Erwerbs.",
    method: "Das UI verdichtet die gesetzlichen Tarifstufen zu einem explizit gekennzeichneten durchschnittlichen Modellsteuersatz.",
    limitations: ["Steuerklassen, Zehnjahreszeiträume und sämtliche sachlichen Befreiungen sind noch nicht als Einzelfälle abgebildet.", "Betriebsvermögensregeln werden pauschalisiert."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-wealth",
    title: "Vermögensteuergesetz",
    institution: "Bundesministerium der Justiz / Bundesamt für Justiz",
    url: "https://www.gesetze-im-internet.de/vstg_1974/",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Rechtsquelle zum Vermögensteuergesetz; in der Anwendung wird keine laufende Baseline-Erhebung unterstellt.",
    method: "Die Vermögensteuer startet bei null und wird ausschließlich als hypothetisches Szenario mit offengelegter Bemessungsgrundlage berechnet.",
    limitations: ["Keine amtlich festgestellte aktuelle Bemessungsgrundlage.", "Bewertung, Ausweichreaktionen und Unternehmensvermögen sind besonders unsicher."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-social-insurance",
    title: "Sozialversicherungsrechengrößen und Beitragssätze 2026",
    institution: "Bundesministerium für Arbeit und Soziales / Deutsche Rentenversicherung",
    url: "https://www.bmas.de/DE/Service/Presse/Pressemitteilungen/2025/das-aendert-sich-im-neuen-jahr.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Beitragssätze und Beitragsbemessungsgrenze der Renten- und Arbeitslosenversicherung für 2026.",
    method: "Renten- und Arbeitslosenbeitrag sowie jährliche Beitragsbemessungsgrenze werden als Baseline-Parameter übernommen.",
    limitations: ["Sonderregelungen, Minijobs und Personengruppen mit abweichender Versicherungspflicht sind noch nicht einzeln abgebildet."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-health-contributions",
    title: "Beiträge und Beitragsbemessungsgrenze der Kranken- und Pflegeversicherung 2026",
    institution: "Bundesministerium für Gesundheit",
    url: "https://www.bundesgesundheitsministerium.de/beitraege",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Allgemeiner GKV-Beitragssatz, durchschnittlicher Zusatzbeitrag und Rechengrößen 2026.",
    method: "Das Modell verwendet 14,6 Prozent allgemeinen Beitrag plus 2,9 Prozent durchschnittlichen Zusatzbeitrag sowie 3,6 Prozent Pflegebeitrag als Baseline.",
    limitations: ["Tatsächliche Zusatzbeiträge unterscheiden sich zwischen Krankenkassen.", "Kinderlosenzuschlag und Abschläge nach Kinderzahl werden noch nicht in einer Bevölkerung verteilt."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-corporate-tax",
    title: "Körperschaftsteuer",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundesfinanzministerium.de/Content/DE/Glossareintraege/K/koerperschaftsteuer.html?view=renderHelp",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Beschreibung des Körperschaftsteuersatzes von 15 Prozent.",
    method: "Tarifsatz und Solidaritätszuschlag werden auf eine kalibrierte aggregierte Bemessungsgrundlage angewandt.",
    limitations: ["Gewerbesteuer bleibt ein separates Haushaltsaggregat.", "Organschaften, internationale Mindeststeuer und Detailregeln der Verlustverrechnung sind nicht vollständig enthalten."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-capital-tax",
    title: "Einzelfragen zur Abgeltungsteuer",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Abgeltungsteuer/2025-05-14-einzelfragen-zur-abgeltungsteuer.pdf?__blob=publicationFile&v=2",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Verwaltungsgrundlage zum Abgeltungsteuersatz von 25 Prozent und zur Besteuerung von Kapitalerträgen.",
    method: "Der Satz wird mit einem Sparer-Pauschbetrag und einer verdichteten Verlustverrechnungsquote kombiniert.",
    limitations: ["Günstigerprüfung, Kirchensteuer, Investmentsteuer und einzelne Verlustverrechnungstöpfe sind nicht vollständig enthalten."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-energy-taxes",
    title: "Energie- und Verbrauchsteuern",
    institution: "Generalzolldirektion",
    url: "https://www.zoll.de/DE/Fachthemen/Steuern/Verbrauchsteuern/Energie/energie_node.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Informationen zu Energieerzeugnissen und Verbrauchsteuern.",
    method: "Wegen unterschiedlicher Mengeneinheiten nutzt das Szenario getrennte Indizes für Kraftstoffe, Strom, Tabak und Alkohol.",
    limitations: ["Keine produktgenaue Mengenbasis.", "Temporäre Entlastungen und zahlreiche Begünstigungen werden nicht einzeln modelliert."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-revenue-model",
    title: "DE-SIM Modellvertrag für weitere Einnahmen",
    institution: "DE-SIM Projekt",
    url: "https://kevni92.github.io/de-sim-docs/",
    dataYear: 2025,
    legalYear: 2026,
    status: "modell",
    confidence: "mittel",
    summary: "Versionierte Aggregatmodelle für statische Aufkommenswirkungen, Verhaltensanpassungen und Inzidenzannahmen.",
    method: "Jedes Modul trennt Baseline, statische Wirkung und Verhaltenskomponente. Parameter, Formeln und Grenzen werden einzeln ausgewiesen.",
    limitations: ["Noch keine repräsentative Mikrosimulation für diese Module.", "Inzidenz und Elastizitäten sind Szenarioannahmen und keine Prognosen."],
    checkedAt: "2026-07-13",
  },
];

const changeLog = [
  { date: "2026-07-13", version: "0.5.0", note: "Sieben weitere Einnahmemodule mit gemeinsamer Modell- und Transparenzschnittstelle eingeführt." },
];

const metric = (
  id: string,
  label: string,
  description: string,
  sourceIds: string[],
  formula: string,
  parameters: MetricRecord["parameters"],
  limitations: string[],
  uncertainty: number,
  confidence: MetricRecord["confidence"] = "mittel",
): MetricRecord => ({
  id,
  label,
  category: "Weitere Einnahmen",
  description,
  unit: "Mrd. € pro Jahr",
  status: "modell",
  confidence,
  dataYear: 2025,
  legalYear: 2026,
  sourceIds,
  formula,
  parameters,
  calculation: [
    { label: "Baseline", expression: "R₀ = veröffentlichtes und gerundetes Ausgangsaggregat" },
    { label: "Statische Wirkung", expression: "Rₛ = f(Baseline, Szenarioparameter)" },
    { label: "Verhaltenskomponente", expression: "R = Rₛ − ΔRₛ × Sensitivität × Modellstufe" },
  ],
  uncertainty: { kind: "band", lowerPercent: -uncertainty, upperPercent: uncertainty, description: "Bandbreite für aggregierte Bemessungsgrundlage, Parametrisierung und Verhaltensannahmen." },
  limitations,
  changeLog,
});

export const revenueModuleMetrics: MetricRecord[] = [
  metric(
    "metric-revenue-ust",
    "Aufkommen der Umsatzsteuer",
    "Szenarioaufkommen aus Regelsteuersatz, ermäßigtem Steuersatz, Anteil ermäßigter Umsätze und Preisweitergabe.",
    ["source-vat", "source-budget", "source-revenue-model"],
    "Rₛ = 291,4 × gewichteter Satz Szenario / gewichteter Satz Baseline",
    [
      { name: "Regelsteuersatz", value: "19 % Baseline", sourceId: "source-vat" },
      { name: "Ermäßigter Steuersatz", value: "7 % Baseline", sourceId: "source-vat" },
      { name: "Anteil ermäßigter Umsätze", value: "32 % Modellannahme", sourceId: "source-revenue-model" },
    ],
    ["Kein detaillierter Warenkorb.", "Steuerbefreiungen und Vorsteuerabzug nur im Ausgangsaggregat.", "Preisweitergabe ist eine Szenarioannahme."],
    12,
  ),
  metric(
    "metric-revenue-erb",
    "Aufkommen der Erbschaft- und Schenkungsteuer",
    "Verdichtete Wirkung von durchschnittlichem Modellsteuersatz, Referenzfreibetrag und Betriebsvermögensverschonung.",
    ["source-inheritance", "source-budget", "source-revenue-model"],
    "Rₛ = 11,8 × Satzfaktor × Freibetragsfaktor × Verschonungsfaktor",
    [
      { name: "Gesetzliche Tarifspanne", value: "nach § 19 ErbStG", sourceId: "source-inheritance" },
      { name: "Durchschnittlicher Modellsteuersatz", value: "19 % Baseline", sourceId: "source-revenue-model" },
    ],
    ["Keine vollständige Einzelfallberechnung nach Steuerklassen.", "Betriebsvermögen und Schenkungszeiträume sind pauschalisiert."],
    30,
    "niedrig",
  ),
  metric(
    "metric-revenue-verm",
    "Szenarioaufkommen einer Vermögensteuer",
    "Hypothetisches Aufkommen einer derzeit nicht erhobenen Vermögensteuer.",
    ["source-wealth", "source-revenue-model"],
    "Rₛ = modellierte steuerpflichtige Vermögensbasis × Steuersatz",
    [
      { name: "Baseline-Aufkommen", value: "0 Mrd. €", sourceId: "source-wealth" },
      { name: "Modellierte Vermögensbasis", value: "1.100 Mrd. € vor Freibetrags- und Bewertungsfaktoren", sourceId: "source-revenue-model" },
    ],
    ["Keine amtlich festgestellte aktuelle Bemessungsgrundlage.", "Hohe Unsicherheit bei Bewertung, Ausweichreaktionen und Unternehmensvermögen."],
    45,
    "niedrig",
  ),
  metric(
    "metric-revenue-sozb",
    "Aufkommen der Sozialversicherungsbeiträge",
    "Aggregiertes Beitragsaufkommen aus vier Versicherungszweigen und zwei Beitragsbemessungsgrenzen.",
    ["source-social-insurance", "source-health-contributions", "source-budget", "source-revenue-model"],
    "Rₛ = 620 × Beitragssatzfaktor × gewichteter BBG-Faktor",
    [
      { name: "Rentenversicherung", value: "18,6 %", sourceId: "source-social-insurance" },
      { name: "Krankenversicherung", value: "14,6 % + 2,9 % Zusatzbeitrag", sourceId: "source-health-contributions" },
      { name: "Pflegeversicherung", value: "3,6 % Grundbeitrag", sourceId: "source-health-contributions" },
      { name: "Arbeitslosenversicherung", value: "2,6 %", sourceId: "source-social-insurance" },
    ],
    ["Keine vollständige Verteilung auf versicherte Personen.", "Sonderregeln, Kinderlosenzuschlag und kassenspezifische Zusatzbeiträge sind nicht vollständig abgebildet."],
    10,
  ),
  metric(
    "metric-revenue-kst",
    "Aufkommen der Körperschaftsteuer",
    "Aggregiertes Körperschaftsteueraufkommen mit Solidaritätszuschlag, Verlustverrechnung und Investitionsabzügen.",
    ["source-corporate-tax", "source-budget", "source-revenue-model"],
    "Rₛ = 46,1 × effektiver Satzfaktor × Verlustfaktor × Abzugsfaktor",
    [
      { name: "Körperschaftsteuersatz", value: "15 % Baseline", sourceId: "source-corporate-tax" },
      { name: "Solidaritätszuschlag", value: "5,5 % auf die Körperschaftsteuer", sourceId: "source-revenue-model" },
    ],
    ["Gewerbesteuer bleibt separat.", "Internationale Gewinnverlagerung und Detailregeln sind nur über eine Elastizitätsannahme berücksichtigt."],
    28,
  ),
  metric(
    "metric-revenue-kap",
    "Aufkommen der Kapitalertragsteuer",
    "Aggregiertes Aufkommen aus Abgeltungsteuersatz, Sparer-Pauschbetrag und Verlustverrechnung.",
    ["source-capital-tax", "source-budget", "source-revenue-model"],
    "Rₛ = 9,8 × Satzfaktor × Freibetragsfaktor × Verlustfaktor",
    [
      { name: "Abgeltungsteuersatz", value: "25 % Baseline", sourceId: "source-capital-tax" },
      { name: "Sparer-Pauschbetrag", value: "1.000 € Referenzfall", sourceId: "source-revenue-model" },
    ],
    ["Keine Günstigerprüfung.", "Investmentsteuer, Kirchensteuer und Verlustverrechnungstöpfe sind verdichtet."],
    35,
    "niedrig",
  ),
  metric(
    "metric-revenue-energie",
    "Aufkommen der Energie- und Verbrauchsteuern",
    "Indexbasiertes Aufkommen für Kraftstoffe, Strom, Tabak und Alkohol.",
    ["source-energy-taxes", "source-budget", "source-revenue-model"],
    "Rₛ = 63,2 × gewichteter Belastungsindex / 100",
    [
      { name: "Kraftstoffgewicht", value: "45 %", sourceId: "source-revenue-model" },
      { name: "Stromgewicht", value: "15 %", sourceId: "source-revenue-model" },
      { name: "Tabakgewicht", value: "28 %", sourceId: "source-revenue-model" },
      { name: "Alkoholgewicht", value: "12 %", sourceId: "source-revenue-model" },
    ],
    ["Indexmodell statt produktgenauer Mengenrechnung.", "Temporäre Entlastungen und Begünstigungen sind nicht einzeln enthalten."],
    30,
    "niedrig",
  ),
];
