import type { SourceRecord } from "./types";
import { SGB2_SOURCE_IDS } from "./sgb2-policy";

export const sgb2PolicySources: SourceRecord[] = [
  {
    id: SGB2_SOURCE_IDS.law,
    title: "Sozialgesetzbuch Zweites Buch – Grundsicherung für Arbeitsuchende",
    institution: "Bundesministerium der Justiz und Bundesamt für Justiz",
    url: "https://www.gesetze-im-internet.de/sgb_2/",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Aktuelle gesetzliche Grundlage für Anspruch, Bedarf, Einkommen, Vermögen, Unterkunft und Leistungsminderungen.",
    method: "Die Policy-Verträge verweisen auf stabile Parameter- und Regel-IDs; der jeweilige Rechtsstand und Gültigkeitszeitraum werden separat gespeichert.",
    limitations: ["Ein Gesetzestext ersetzt keine verwaltungsrechtliche Einzelfallentscheidung.", "Übergangs- und Sonderregeln müssen im jeweiligen Rechenmodul ausdrücklich implementiert werden."],
    checkedAt: "2026-07-13",
  },
  {
    id: SGB2_SOURCE_IDS.ruleRates2026,
    title: "Regelbedarfe in Sozialhilfe und Grundsicherung 2026",
    institution: "Bundesministerium für Arbeit und Soziales",
    url: "https://www.bmas.de/DE/Service/Presse/Pressemitteilungen/2025/fortschreibung-regelbedarfe-sozialhilfe-und-buergergeld.html",
    dataYear: 2026,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Fortschreibung der monatlichen Regelbedarfsstufen für 2026.",
    method: "Die Eurobeträge werden als ganzzahlige Cent pro Person und Monat in der Policy gespeichert.",
    limitations: ["Unterkunft, Heizung und individuelle Mehrbedarfe sind nicht Bestandteil des Regelbedarfsbetrags."],
    checkedAt: "2026-07-13",
  },
  {
    id: SGB2_SOURCE_IDS.statistics,
    title: "Statistik der Grundsicherung für Arbeitsuchende",
    institution: "Bundesagentur für Arbeit – Statistik",
    url: "https://statistik.arbeitsagentur.de/",
    dataYear: 2025,
    legalYear: 2026,
    status: "amtlich",
    confidence: "hoch",
    summary: "Amtliche Bestands-, Zahlungsanspruchs- und Strukturstatistiken für spätere Kalibrierung und Abgleich.",
    method: "Statistikstand und Rechtsstand werden getrennt geführt; Bestände werden nicht pauschal als Jahresflüsse interpretiert.",
    limitations: ["Berichtsperioden und gesetzliche Rechtsstände können voneinander abweichen.", "Statistische Aggregate enthalten nicht jede für eine Einzelfallberechnung benötigte gemeinsame Verteilung."],
    checkedAt: "2026-07-13",
  },
  {
    id: "source-bundeshaushalt-2024-sgb2",
    title: "Bundeshaushalt 2024 – Bürgergeld und Bundesbeteiligung an Unterkunft und Heizung",
    institution: "Bundesministerium der Finanzen",
    url: "https://www.bundeshaushalt.de/",
    dataYear: 2024,
    legalYear: 2024,
    status: "amtlich",
    confidence: "hoch",
    summary: "Ist-Ausgaben der Titel 1101 681 12 und 1101 632 11 als externer Release-Prüfanker.",
    method: "Der sechsmonatige Modell-Referenzlauf wird auf zwölf Monate annualisiert und ohne Kalibrierung mit der amtlichen Haushaltsabgrenzung verglichen.",
    limitations: ["Haushaltsjahr 2024 und Rechtsstand Juli 2026 sind nur teilweise vergleichbar.", "Die Haushaltstitel trennen Regelbedarf und Mehrbedarfe beziehungsweise Unterkunft und Heizung nicht in derselben Granularität wie das Modell."],
    checkedAt: "2026-07-14",
  },
  {
    id: SGB2_SOURCE_IDS.housingModel,
    title: "HaushaltsKompass-Modellvertrag für Unterkunft und Heizung",
    institution: "HaushaltsKompass-Projekt",
    url: "https://kevni92.github.io/de-sim-docs/02-fiskal/buergergeld-modul/",
    dataYear: 2026,
    legalYear: 2026,
    status: "modell",
    confidence: "niedrig",
    summary: "Technischer Fallback und Schema für regionale Angemessenheitsgrenzen, solange kommunale Datensätze noch nicht eingebunden sind.",
    method: "Regionale KdU-Datensätze bleiben von bundesweiten Leistungsparametern getrennt und tragen Status, Quelle, Gültigkeit und Unsicherheit.",
    limitations: ["Der erste Fallback enthält bewusst keine kommunalen Miet- oder Heizkostengrenzen.", "Fehlende regionale Werte dürfen später nicht als null Euro interpretiert werden."],
    checkedAt: "2026-07-13",
  },
];
