import { Trash2 } from "lucide-react";
import { createContext, useContext, useMemo, useState } from "react";
import { ConfidenceIndicator, EvidenceSourceButton } from "../components/EvidenceTooltip";
import { icons, type IconName } from "../components/icons";
import { expenseLineResultsById, expenseModuleForLineId, expenseResultsById, type ExpenseModuleId, type ExpenseModuleResult } from "../lib/expense-modules";
import type { IncomeTaxResult } from "../lib/income-tax";
import { revenueModuleIds, revenueResultsById, type RevenueModuleId, type RevenueModuleResult } from "../lib/revenue-modules";
import { expenseItems, fmtBn, fmtDiff, revenueItems } from "../lib/sim-data";
import type { MetricRecord, ScenarioState, SourceRecord } from "../lib/types";

type Tab = "budget" | "haushalte" | "verteilung" | "regionen" | "zeit";
type MobileTab = "steuern" | "ergebnis" | "ausgaben" | "szenario";
type RevenueLine = (typeof revenueItems)[number] & { value: number; delta: number };
type ExpenseLine = (typeof expenseItems)[number] & { value: number; delta: number };
type EvidenceContextValue = { metricsById: Record<string, MetricRecord>; sources: SourceRecord[] };

const EvidenceContext = createContext<EvidenceContextValue>({ metricsById: {}, sources: [] });

type Props = {
  incomeTaxResult: IncomeTaxResult;
  revenueModuleResults: RevenueModuleResult[];
  expenseModuleResults: ExpenseModuleResult[];
  metrics: MetricRecord[];
  sources: SourceRecord[];
  scenarios: ScenarioState[];
  onNavigateIncomeTax: () => void;
  onNavigateRevenue: (id: RevenueModuleId) => void;
  onNavigateExpense: (id: ExpenseModuleId) => void;
  onNavigateComparison: () => void;
  onOpenSource: (metricId: string, value?: string) => void;
  onLoadScenario: (scenario: ScenarioState) => void;
  onDeleteScenario: (scenario: ScenarioState) => void;
};

export function DashboardPage({ incomeTaxResult, revenueModuleResults, expenseModuleResults, metrics, sources, scenarios, onNavigateIncomeTax, onNavigateRevenue, onNavigateExpense, onNavigateComparison, onOpenSource, onLoadScenario, onDeleteScenario }: Props) {
  const [tab, setTab] = useState<Tab>("budget");
  const [mobileTab, setMobileTab] = useState<MobileTab>("ergebnis");
  const revenueById = useMemo(() => revenueResultsById(revenueModuleResults), [revenueModuleResults]);
  const expenseLines = useMemo(() => expenseLineResultsById(expenseModuleResults), [expenseModuleResults]);
  const expenseById = useMemo(() => expenseResultsById(expenseModuleResults), [expenseModuleResults]);
  const evidence = useMemo<EvidenceContextValue>(() => ({ metricsById: Object.fromEntries(metrics.map((metric) => [metric.id, metric])), sources }), [metrics, sources]);

  const revenues = useMemo<RevenueLine[]>(() => revenueItems.map((item) => {
    if (item.id === "est") return { ...item, value: incomeTaxResult.value, delta: incomeTaxResult.delta };
    if (revenueModuleIds.includes(item.id as RevenueModuleId)) { const result = revenueById[item.id as RevenueModuleId]; return { ...item, value: result.value, delta: result.delta }; }
    return { ...item, value: item.statusQuo, delta: 0 };
  }), [incomeTaxResult.delta, incomeTaxResult.value, revenueById]);
  const expenses = useMemo<ExpenseLine[]>(() => expenseItems.map((item) => ({ ...item, value: expenseLines[item.id]?.value ?? item.statusQuo, delta: expenseLines[item.id]?.delta ?? 0 })), [expenseLines]);

  const revenueTotal = revenues.reduce((sum, item) => sum + item.value, 0);
  const revenueStatusQuo = revenueItems.reduce((sum, item) => sum + item.statusQuo, 0);
  const expenseTotal = expenses.reduce((sum, item) => sum + item.value, 0);
  const expenseStatusQuo = expenseItems.reduce((sum, item) => sum + item.statusQuo, 0);
  const balance = revenueTotal - expenseTotal;
  const balanceStatusQuo = revenueStatusQuo - expenseStatusQuo;
  const totalRevenueDelta = incomeTaxResult.delta + revenueModuleResults.reduce((sum, item) => sum + item.delta, 0);
  const totalExpenseDelta = expenseModuleResults.reduce((sum, item) => sum + item.delta, 0);
  const totalBudgetDelta = totalRevenueDelta - totalExpenseDelta;

  const openRevenueItem = (itemId: string) => itemId === "est" ? onNavigateIncomeTax() : revenueModuleIds.includes(itemId as RevenueModuleId) ? onNavigateRevenue(itemId as RevenueModuleId) : undefined;
  const openExpenseItem = (itemId: string) => { const moduleId = expenseModuleForLineId[itemId]; if (moduleId) onNavigateExpense(moduleId); };
  const centerProps = { tab, setTab, incomeTaxResult, revenueModuleResults, expenseModuleResults, totalRevenueDelta, totalExpenseDelta, totalBudgetDelta, onOpenSource, onNavigateComparison, onNavigateExpense, onLoadScenario, onDeleteScenario };

  return <EvidenceContext.Provider value={evidence}><>
    <section className="sticky-kpis" aria-label="Haushaltsübersicht"><div className="content-width kpi-grid">
      <KpiCard label="Einnahmen" metricId="metric-total-revenue" value={fmtBn(revenueTotal)} delta={fmtDiff(revenueTotal - revenueStatusQuo)} tone={revenueTotal >= revenueStatusQuo ? "positive" : "negative"} onSource={() => onOpenSource("metric-total-revenue", fmtBn(revenueTotal))} />
      <KpiCard label="Ausgaben" metricId="metric-total-expense" value={fmtBn(expenseTotal)} delta={fmtDiff(expenseTotal - expenseStatusQuo)} tone={expenseTotal <= expenseStatusQuo ? "positive" : "negative"} onSource={() => onOpenSource("metric-total-expense", fmtBn(expenseTotal))} />
      <KpiCard label="Saldo" metricId="metric-budget-balance" value={fmtBn(balance)} delta={fmtDiff(balance - balanceStatusQuo)} tone={balance >= balanceStatusQuo ? "positive" : "negative"} onSource={() => onOpenSource("metric-budget-balance", fmtBn(balance))} />
      <KpiCard label="Schuldenstand" metricId="metric-public-debt" value="2.634,0 Mrd. €" delta={fmtDiff(Math.max(0, -(balance - balanceStatusQuo)))} tone="warning" onSource={() => onOpenSource("metric-public-debt", "2.634,0 Mrd. €")} />
    </div></section>

    <main className="content-width dashboard-main">
      <div className="desktop-dashboard"><LinePanel title="Einnahmen" total={revenueTotal} totalMetricId="metric-total-revenue" items={revenues} onOpenSource={onOpenSource} onInteractive={openRevenueItem} isInteractive={(id) => id === "est" || revenueModuleIds.includes(id as RevenueModuleId)} /><CenterPanel {...centerProps} scenarios={scenarios} migration={expenseById.migration} /><LinePanel title="Ausgaben" total={expenseTotal} totalMetricId="metric-total-expense" items={expenses} expense onOpenSource={onOpenSource} onInteractive={openExpenseItem} isInteractive={(id) => Boolean(expenseModuleForLineId[id])} /></div>
      <div className="mobile-dashboard"><div className="mobile-tabs" role="tablist" aria-label="Dashboardbereiche">{([ ["steuern", "Steuern"], ["ergebnis", "Ergebnis"], ["ausgaben", "Ausgaben"], ["szenario", "Szenario"] ] as const).map(([key, label]) => <button key={key} role="tab" aria-selected={mobileTab === key} className={mobileTab === key ? "active" : ""} onClick={() => setMobileTab(key)}>{label}</button>)}</div><div className="mobile-tab-content">
        {mobileTab === "steuern" && <LinePanel title="Einnahmen" total={revenueTotal} totalMetricId="metric-total-revenue" items={revenues} onOpenSource={onOpenSource} onInteractive={openRevenueItem} isInteractive={(id) => id === "est" || revenueModuleIds.includes(id as RevenueModuleId)} />}
        {mobileTab === "ergebnis" && <CenterPanel {...centerProps} scenarios={[]} migration={expenseById.migration} />}
        {mobileTab === "ausgaben" && <LinePanel title="Ausgaben" total={expenseTotal} totalMetricId="metric-total-expense" items={expenses} expense onOpenSource={onOpenSource} onInteractive={openExpenseItem} isInteractive={(id) => Boolean(expenseModuleForLineId[id])} />}
        {mobileTab === "szenario" && <SavedScenarios scenarios={scenarios} onLoad={onLoadScenario} onDelete={onDeleteScenario} />}
      </div></div>
    </main>
    <footer className="app-footer content-width">Einnahmen und Ausgaben werden als getrennte Module berechnet. Direkte Haushaltswirkung, Folgewirkung, Unsicherheit und Quellen bleiben sichtbar.</footer>
  </></EvidenceContext.Provider>;
}

function KpiCard({ label, metricId, value, delta, tone, onSource }: { label: string; metricId: string; value: string; delta: string; tone: "positive" | "negative" | "warning" | "neutral"; onSource: () => void }) { return <article className="card-flat kpi-card"><div className="kpi-head"><span>{label}</span><SourceButton contextLabel={label} metricId={metricId} onClick={onSource} /></div><div className="kpi-value-row"><strong>{value}</strong><em className={tone}>{delta}</em></div><small>{label === "Schuldenstand" ? "rd. 62,1 % des BIP · Bandbreite ± 4 %" : "Bund, Länder, Kommunen, Sozialversicherung"}</small></article>; }

function LinePanel({ title, total, totalMetricId, items, expense = false, onOpenSource, onInteractive, isInteractive }: { title: string; total: number; totalMetricId: string; items: Array<RevenueLine | ExpenseLine>; expense?: boolean; onOpenSource: (metricId: string, value?: string) => void; onInteractive?: (itemId: string) => void; isInteractive?: (itemId: string) => boolean }) {
  const statusQuo = items.reduce((sum, item) => sum + item.statusQuo, 0);
  const totalPositive = expense ? total <= statusQuo : total >= statusQuo;
  return <aside className="card-flat line-panel" aria-label={title}><header><div className="panel-title-row"><h2>{title}</h2><SourceButton contextLabel={title} metricId={totalMetricId} onClick={() => onOpenSource(totalMetricId, fmtBn(total))} /></div><div className="panel-total"><strong>{fmtBn(total)}</strong><em className={totalPositive ? "positive" : "negative"}>{fmtDiff(total - statusQuo)}</em></div>{expense && <p>direkte Ausgaben sowie separat ausgewiesene Steuervergünstigungen</p>}</header><ul>{items.map((item) => { const interactive = Boolean(onInteractive && isInteractive?.(item.id)); const metricId = metricIdForLine(item.id); return <LineRow key={item.id} item={item} metricId={metricId} expense={expense} onClick={interactive ? () => onInteractive?.(item.id) : undefined} onSource={() => onOpenSource(metricId, fmtBn(item.value))} />; })}</ul></aside>;
}

function metricIdForLine(itemId: string) { if (itemId === "est") return "metric-income-tax-revenue"; if (revenueModuleIds.includes(itemId as RevenueModuleId)) return `metric-revenue-${itemId}`; if (expenseModuleForLineId[itemId]) return `metric-expense-${expenseModuleForLineId[itemId]}`; if (itemId === "kredit") return "metric-budget-balance"; return "metric-public-budget-lines"; }
function LineRow({ item, metricId, expense, onClick, onSource }: { item: RevenueLine | ExpenseLine; metricId: string; expense: boolean; onClick?: () => void; onSource: () => void }) { const Icon = icons[item.icon as IconName]; const positive = expense ? item.delta <= 0 : item.delta >= 0; return <li className={`${item.delta !== 0 ? "changed" : ""} ${item.confidence === "niedrig" ? "uncertain" : ""}`}><button className="line-row-main" onClick={onClick} disabled={!onClick} aria-label={onClick ? `${item.label} bearbeiten` : undefined}><span className={`category-icon ${expense ? "expense" : ""}`}><Icon size={14} strokeWidth={1.8} /></span><span className="line-copy"><strong>{item.label}</strong><small>{fmtBn(item.statusQuo)} → <b>{fmtBn(item.value)}</b>{"note" in item && item.note ? ` · ${item.note}` : ""}</small></span></button><span className="line-side"><em className={item.delta === 0 ? "neutral" : positive ? "positive" : "negative"}>{fmtDiff(item.delta)}</em><ConfidenceIndicator confidence={item.confidence} /><SourceButton contextLabel={item.label} iconOnly metricId={metricId} onClick={onSource} /></span></li>; }

type CenterProps = { tab: Tab; setTab: (tab: Tab) => void; incomeTaxResult: IncomeTaxResult; revenueModuleResults: RevenueModuleResult[]; expenseModuleResults: ExpenseModuleResult[]; totalRevenueDelta: number; totalExpenseDelta: number; totalBudgetDelta: number; onOpenSource: (metricId: string, value?: string) => void; onNavigateComparison: () => void; onNavigateExpense: (id: ExpenseModuleId) => void; scenarios: ScenarioState[]; migration: ExpenseModuleResult; onLoadScenario: (scenario: ScenarioState) => void; onDeleteScenario: (scenario: ScenarioState) => void };
function CenterPanel(props: CenterProps) { const { tab, setTab, incomeTaxResult, revenueModuleResults, expenseModuleResults, totalRevenueDelta, totalExpenseDelta, totalBudgetDelta, onOpenSource, onNavigateComparison, onNavigateExpense, scenarios, migration, onLoadScenario, onDeleteScenario } = props; return <section className="center-panel"><div className="card-flat result-card"><div className="result-tabs">{([ ["budget", "Budget"], ["haushalte", "Haushalte"], ["verteilung", "Verteilung"], ["regionen", "Regionen"], ["zeit", "Zeitverlauf"] ] as const).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}<div className="result-tabs-actions"><span className="scenario-chip">8 Einnahmen · 9 Ausgaben</span><button className="button secondary small" onClick={onNavigateComparison}>Vergleich öffnen</button></div></div><div className="result-content">{tab === "budget" && <BudgetTab result={incomeTaxResult} revenueModules={revenueModuleResults} expenseModules={expenseModuleResults} revenueDelta={totalRevenueDelta} expenseDelta={totalExpenseDelta} budgetDelta={totalBudgetDelta} onOpenSource={onOpenSource} />}{tab === "haushalte" && <HouseholdsTab result={incomeTaxResult} onOpenSource={onOpenSource} />}{tab === "verteilung" && <DistributionTab result={incomeTaxResult} onOpenSource={onOpenSource} />}{tab === "regionen" && <RegionsTab onOpenSource={onOpenSource} />}{tab === "zeit" && <TimeTab totalDelta={totalBudgetDelta} onOpenSource={onOpenSource} />}</div></div><MigrationCard result={migration} onOpenSource={onOpenSource} onOpen={() => onNavigateExpense("migration")} />{scenarios.length > 0 && <SavedScenarios scenarios={scenarios} onLoad={onLoadScenario} onDelete={onDeleteScenario} />}</section>; }

function BudgetTab({ result, revenueModules, expenseModules, revenueDelta, expenseDelta, budgetDelta, onOpenSource }: { result: IncomeTaxResult; revenueModules: RevenueModuleResult[]; expenseModules: ExpenseModuleResult[]; revenueDelta: number; expenseDelta: number; budgetDelta: number; onOpenSource: (metricId: string, value?: string) => void }) {
  const staticBudget = result.staticDelta + revenueModules.reduce((sum, item) => sum + item.staticDelta, 0) - expenseModules.reduce((sum, item) => sum + item.staticDelta, 0);
  const feedbackBudget = result.behavioralAdjustment + revenueModules.reduce((sum, item) => sum + item.behavioralAdjustment, 0) - expenseModules.reduce((sum, item) => sum + item.feedbackAdjustment, 0);
  return <div className="budget-layout"><div><div className="section-title"><div><h3>Wasserfall Budgetsaldo</h3><p>Gemeinsame Wirkung aller aktiven Einnahmen- und Ausgabenmodule.</p></div><SourceButton contextLabel="Wasserfall Budgetsaldo" metricId="metric-budget-balance" onClick={() => onOpenSource("metric-budget-balance", fmtDiff(budgetDelta))} /></div><Waterfall revenueDelta={revenueDelta} expenseDelta={expenseDelta} /><div className="plain-language">Die aktiven Parameter verändern den Haushaltssaldo um <strong>{fmtDiff(budgetDelta)} pro Jahr</strong>: Einnahmen {fmtDiff(revenueDelta)}, Ausgaben {fmtDiff(expenseDelta)}.</div></div><div><h3>Direkt und mit Rückwirkung</h3><p className="section-description">Erstwirkung und modellierte Anpassung bleiben getrennt.</p><div className="budget-model-compare"><span><b>{fmtDiff(staticBudget)}</b>direkte Budgetwirkung</span><span><b>{fmtDiff(feedbackBudget)}</b>Verhaltens- und Folgewirkung</span><span><b>{expenseModules.length + revenueModules.length + 1}</b>Modellmodule</span></div><div className="module-delta-list">{expenseModules.map((item) => <span key={item.id}><small>{item.label}</small><b className={item.delta <= 0 ? "positive" : "negative"}>{fmtDiff(-item.delta)} Saldo</b></span>)}</div></div></div>;
}
function Waterfall({ revenueDelta, expenseDelta }: { revenueDelta: number; expenseDelta: number }) { const budgetDelta = revenueDelta - expenseDelta; const newBalance = -39 + budgetDelta; const bars = [{ label: "Saldo Status quo", value: -39, tone: "total" }, { label: "Einnahmen", value: revenueDelta, tone: revenueDelta >= 0 ? "positive" : "negative" }, { label: "Ausgaben", value: -expenseDelta, tone: expenseDelta <= 0 ? "positive" : "negative" }, { label: "Saldo Szenario", value: newBalance, tone: "total" }]; return <div className="waterfall" role="img" aria-label="Wasserfalldiagramm des Budgetsaldos">{bars.map((bar) => <div className="waterfall-col" key={bar.label}><span>{bar.value.toLocaleString("de-DE", { maximumFractionDigits: 1 })}</span><i className={bar.tone} style={{ height: `${Math.max(28, Math.min(180, Math.abs(bar.value) * 2.4))}px` }} /><small>{bar.label}</small></div>)}</div>; }
function HouseholdsTab({ result, onOpenSource }: { result: IncomeTaxResult; onOpenSource: (metricId: string, value?: string) => void }) { return <div><div className="section-title"><div><h3>Referenzhaushalte · Einkommensteuer</h3><p className="section-description">Leistungs- und Ausgabenmodule erhalten eine gemeinsame Haushaltsverteilung mit der synthetischen Bevölkerung.</p></div><SourceButton contextLabel="Referenzhaushalte" metricId="metric-household-examples" onClick={() => onOpenSource("metric-household-examples", formatSignedEuro(result.medianMonthlyChange))} /></div><div className="household-grid">{result.households.map((household) => <article className="household-card" key={household.id}><div><strong>{household.name}</strong><small>{household.description}</small></div><em className={household.monthlyChange >= 0 ? "positive" : "negative"}>{formatSignedEuro(household.monthlyChange)} / Monat</em><p>Gesetz: {formatEuro(household.baselineTax)} · Reform: {formatEuro(household.reformTax)} pro Jahr.</p><span>direkte Tarifwirkung</span></article>)}</div></div>; }
function DistributionTab({ result, onOpenSource }: { result: IncomeTaxResult; onOpenSource: (metricId: string, value?: string) => void }) { const max = Math.max(1, ...result.deciles.map((item) => Math.abs(item.monthlyChange))); return <div><div className="section-title"><div><h3>Nettowirkung nach Einkommensdezilen · Einkommensteuer</h3><p className="section-description">Gewichteter Tarifvergleich der kalibrierten Referenzpopulation.</p></div><SourceButton contextLabel="Nettowirkung nach Einkommensdezilen" metricId="metric-income-tax-distribution" onClick={() => onOpenSource("metric-income-tax-distribution", `${formatNumber(result.winnersM)} Mio. Gewinner`)} /></div><div className="distribution-bars">{result.deciles.map((item) => { const positive = item.monthlyChange >= 0; const width = Math.abs(item.monthlyChange) / max * 50; return <div key={item.id}><span>{item.id}</span><i><b className={positive ? "positive" : "negative"} style={{ left: positive ? "50%" : `${50 - width}%`, width: `${width}%` }} /></i><em className={positive ? "positive" : "negative"}>{formatSignedEuro(item.monthlyChange)}</em></div>; })}</div><p className="distribution-summary"><strong>{formatNumber(result.winnersM)} Mio.</strong> Gewinner · <strong>{formatNumber(result.losersM)} Mio.</strong> Verlierer · <strong>{formatNumber(result.neutralM)} Mio.</strong> nahezu unverändert</p></div>; }
function RegionsTab({ onOpenSource }: { onOpenSource: (metricId: string, value?: string) => void }) { const regions = ["Schleswig-Holstein", "Niedersachsen", "Nordrhein-Westfalen", "Hessen", "Sachsen", "Bayern", "Berlin", "Baden-Württemberg"]; return <div><div className="section-title"><div><h3>Regionale Wirkung</h3><p className="section-description">Regionale Kosten- und Leistungsstrukturen folgen mit der synthetischen Bevölkerung.</p></div><SourceButton contextLabel="Regionale Wirkung" metricId="metric-regional-effects" onClick={() => onOpenSource("metric-regional-effects", "noch nicht kalibriert")} /></div><div className="region-layout"><div className="germany-map" aria-label="Stilisierte Deutschlandkarte">{["SH","NI","NW","HE","SN","BY","BE","BW"].map((code) => <span key={code}>{code}</span>)}</div><ul>{regions.map((region) => <li key={region}><span>{region}</span><strong>nicht berechnet</strong></li>)}</ul></div></div>; }
function TimeTab({ totalDelta, onOpenSource }: { totalDelta: number; onOpenSource: (metricId: string, value?: string) => void }) { return <div><div className="section-title"><div><h3>Zeitverlauf</h3><p className="section-description">Schematische Fortschreibung der gesamten Budgetwirkung; keine Konjunkturprognose.</p></div><SourceButton contextLabel="Zeitverlauf" metricId="metric-time-path" onClick={() => onOpenSource("metric-time-path", fmtDiff(totalDelta))} /></div><div className="time-chart">{[2026, 2027, 2028, 2029, 2030, 2031].map((year, index) => <div key={year}><span>{(totalDelta * (1 + index * 0.02)).toLocaleString("de-DE", { maximumFractionDigits: 1 })}</span><i style={{ height: `${60 + index * 15}px` }} /><small>{year}</small></div>)}</div></div>; }
function MigrationCard({ result, onOpenSource, onOpen }: { result: ExpenseModuleResult; onOpenSource: (metricId: string, value?: string) => void; onOpen: () => void }) { return <article className="card-flat migration-card"><div className="section-title"><div><h3>Migration und Asyl · getrennte Teilbereiche</h3><p>Unterbringung, Verfahren, Integration sowie Bildung und weitere Aufgaben bleiben getrennt.</p></div><div><button className="button secondary small" onClick={onOpen}>Modul öffnen</button><SourceButton contextLabel="Migration und Asyl" metricId="metric-expense-migration" onClick={() => onOpenSource("metric-expense-migration", fmtBn(result.value))} /></div></div><div className="migration-grid">{result.components.map((item) => <span key={item.id}><b>{item.value.toLocaleString("de-DE", { maximumFractionDigits: 1 })}</b> {item.label}</span>)}</div></article>; }
function SavedScenarios({ scenarios, onLoad, onDelete }: { scenarios: ScenarioState[]; onLoad: (scenario: ScenarioState) => void; onDelete: (scenario: ScenarioState) => void }) { return <section className="card-flat saved-scenarios"><header><div><span className="eyebrow">Lokaler Worker · IndexedDB</span><h3>Gespeicherte Szenarien</h3></div><strong>{scenarios.length}</strong></header>{scenarios.length === 0 ? <p className="empty-state">Noch kein Szenario gespeichert.</p> : <ul>{scenarios.map((scenario) => <li key={scenario.id}><button onClick={() => onLoad(scenario)}><strong>{scenario.name}</strong><small>{new Date(scenario.updatedAt).toLocaleString("de-DE")}</small></button><button className="plain-icon delete" aria-label={`${scenario.name} löschen`} onClick={() => onDelete(scenario)}><Trash2 size={14} /></button></li>)}</ul>}</section>; }
function SourceButton({ metricId, contextLabel, onClick, iconOnly = false }: { metricId: string; contextLabel: string; onClick: () => void; iconOnly?: boolean }) { const { metricsById, sources } = useContext(EvidenceContext); return <EvidenceSourceButton contextLabel={contextLabel} iconOnly={iconOnly} metric={metricsById[metricId]} sources={sources} onClick={onClick} />; }
function formatNumber(value: number) { return value.toLocaleString("de-DE", { minimumFractionDigits: 1, maximumFractionDigits: 2 }); }
function formatEuro(value: number) { return `${Math.round(value).toLocaleString("de-DE")} €`; }
function formatSignedEuro(value: number) { const sign = value > 0 ? "+" : value < 0 ? "−" : "±"; return `${sign}${Math.abs(Math.round(value)).toLocaleString("de-DE")} €`; }
