import {
  Armchair,
  Baby,
  BadgePercent,
  Briefcase,
  Building2,
  Coins,
  Factory,
  FileText,
  Fuel,
  Gem,
  Globe,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  Percent,
  Receipt,
  Scroll,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Stars,
  Stethoscope,
  TrainFront,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";

export const icons = {
  armchair: Armchair,
  baby: Baby,
  badgepercent: BadgePercent,
  briefcase: Briefcase,
  building: Building2,
  coins: Coins,
  factory: Factory,
  file: FileText,
  fuel: Fuel,
  gem: Gem,
  globe: Globe,
  graduation: GraduationCap,
  hand: HandCoins,
  heart: HeartPulse,
  home: Home,
  landmark: Landmark,
  leaf: Leaf,
  percent: Percent,
  receipt: Receipt,
  scroll: Scroll,
  shield: Shield,
  shieldcheck: ShieldCheck,
  shopping: ShoppingCart,
  stars: Stars,
  stethoscope: Stethoscope,
  train: TrainFront,
  trending: TrendingUp,
  users: Users,
  wallet: Wallet,
};

export type IconName = keyof typeof icons;
